### ISSUE TITLE
Add git tags

### ISSUE THREAD

**Issue by pvnr0082t** [stowball/jQuery-rwdImageMaps#105]
Hi @stowball ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team.
The git auto-updater in cdnjs relies on __[git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging)__ so that it can recognize the correct version and automatically update the repo. 
Could you please add git tags for the repo? Thank you.

https://github.com/cdnjs/cdnjs/issues/9268

**Comment by stowball** [comment]
Done

**Comment by pvnr0082t** [comment]
@stowball Thanks for your help. :facepunch:
