### ISSUE TITLE
Dose this work on the iPad?

### ISSUE THREAD

**Issue by rodoabad** [stowball/jQuery-rwdImageMaps#38]
Here's a test page (only page A1 has areas)...

http://www.eabad-dev.townnews365.com/eedition/page-a/page_882d5827-eef9-5cfe-b637-c39b42463f27.html

Works on the desktop and android devices. On the iPad though, it never reacts to any click events.

If I comment out $('img[usemap]').rwdImageMaps(); it will start working again (click events).

**Comment by dagadzha** [comment]
@haridarshan thank you for posting this fix, it worked for me also. I had the same issue - worked on every browser except Chrome iOS.  I was pulling my hair out for a couple of hours.

**Comment by elproduc3r** [comment]
I found slightly simpler fixed and created new plugin. You dont need to add width and height attributes either - http://theappproducer.com/jmap/#how
