### ISSUE TITLE
$(window).resize(...); loop

### ISSUE THREAD

**Issue by n0ct** [stowball/jQuery-rwdImageMaps#93]
Hello,

Maybe it's not an issue in rwdImageMaps but I can't find an answer to my problem:

On document load I use the following code to properly resize my image map. This works fine.
```javascript
$('img[usemap]').rwdImageMaps();
```
If I resize my windows after the document load, the area will be at a bad place so I would like to do something like:
```javascript
$(window).resize(function(){
     $('img[usemap]').rwdImageMaps();
});
```
But "rwdImageMaps();" function seems to resize the windows so it makes a loop. And rwdImageMaps doesn't handle ".done(function(){...});" so how could I avoid that resize loop ?

**Comment by prabhg** [comment]
I am also experiencing this same issue. 

@n0ct you closed the issue. Did you find another way to fix it?
@stowball this is a valid issue. Will you consider any fix for it?
